# LeafWE Plugin Settings v4.0.3

# General settings for plugin behavior.
settings:
  # Language file to use (e.g., 'en' for messages_en.yml, 'tr' for messages_tr.yml).
  language: 'en'
  # Delay in ticks between each block placement (Lower = Faster, Higher = Slower). 20 ticks = 1 second.
  speed: 2
  # Particle effect to show when a block is placed. Set to 'NONE' to disable.
  # Valid particle names: https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Particle.html
  placement-particle: 'WAX_ON'
  # Enable selection visualization with particles (true/false).
  selection-visualizer: true
  # Require confirmation for operations affecting more blocks than this value. Set to 0 to disable.
  confirmation-limit: 5000
  # The maximum number of undo actions a player can have stored.
  max-undo: 10
  # The maximum volume of blocks a non-admin player can affect at once.
  max-volume: 50000

  # Settings for the success effect after an operation is complete.
  success-effect:
    enabled: true
    sound: 'ENTITY_PLAYER_LEVELUP'

  # Settings for the Pipette (Blockstate Copy) Tool
  pipette-tool:
    enabled: true
    copy-sound: 'ENTITY_ITEM_PICKUP'
    paste-sound: 'BLOCK_NOTE_BLOCK_PLING'

  # Settings for the worker Armor Stand animation.
  worker-animation:
    enabled: true
    show-name: true
    # %player% will be replaced with the player's name.
    name-template: '&a[Worker] %player%'
    # Determines how far above the block the worker stands. (1.5 is ideal)
    y-offset: 1.5
    # The color of the leather armor in R,G,B format.
    armor-color: '0,255,255'

# Properties of the selection wand.
wand-tool:
  material: 'BLAZE_ROD'
  name: '&6Construction Rod'
  lore:
    - '&eUse this to select regions.'
    - '&7Left-Click: Set Position 1'
    - '&7Right-Click: Set Position 2'
    - '&7Crouch + Right-Click: Copy Block State'

# A list of materials that cannot be used with construction commands.
blocked-materials:
  - 'BEDROCK'
  - 'COMMAND_BLOCK'
  - 'TNT'
  - 'AIR'

# LeafWE commands will be disabled in these worlds.
disabled-worlds:
  - 'world_lobby'
  - 'arena'

# Settings for the GUIs
block-selector-gui:
  title: '&1Select a Block'

replace-gui:
  title: '&1Block Replace Menu'
  confirm-button-name: '&a&lCONFIRM & REPLACE'
  confirm-button-lore:
    - '&7Replaces the block in the left slot'
    - '&7with the block in the right slot.'

# Daily Limits System
daily-limits:
  enabled: false  # Set to true to enable daily limits
  reset-time: "00:00"  # Daily reset time (24-hour format)
  groups:
    default:
      max-blocks-per-day: 1000      # Maximum blocks per day
      max-operations-per-day: 10    # Maximum operations per day
    vip:
      max-blocks-per-day: 5000
      max-operations-per-day: 50
    premium:
      max-blocks-per-day: 15000
      max-operations-per-day: 100
    admin:
      max-blocks-per-day: -1        # -1 = unlimited
      max-operations-per-day: -1    # -1 = unlimited

# Permission Groups:
# leafwe.limit.group.default  - Default group (everyone has this)
# leafwe.limit.group.vip      - VIP group
# leafwe.limit.group.premium  - Premium group
# leafwe.limit.group.admin    - Admin group (unlimited)

# Players automatically get the highest permission group they have
# Example: If player has both "vip" and "premium" permissions, they get "premium" limits