name: LeafWE
version: '${project.version}'
main: com.leaf.leafwe.LeafWE
api-version: 1.19
author: BaranMRJ
description: A lightweight WorldEdit alternative for Minecraft servers
website: https://kareblok.tc

# Load after WorldGuard
softdepend: [WorldGuard, SuperiorSkyblock2, Towny, Lands, GriefPrevention, PlotSquared]

commands:
  set:
    description: Fill selected area with blocks
    usage: /<command> <block>
    permission: leafwe.use
  wall:
    description: Create walls around selected area
    usage: /<command> <block>
    permission: leafwe.wall
  replace:
    description: Replace blocks in selected area
    usage: /<command> <from_block> <to_block>
    permission: leafwe.replace
  lwe:
    description: LeafWE main command
    usage: /<command> [reload|give|undo|confirm|limits|resetlimits|givelimits|help]
    aliases: [leafwe]

permissions:
  leafwe.*:
    description: All LeafWE permissions
    children:
      leafwe.use: true
      leafwe.wall: true
      leafwe.replace: true
      leafwe.undo: true
      leafwe.confirm: true
      leafwe.give: true
      leafwe.reload: true
      leafwe.bypass.limit: true
      leafwe.bypass.protection: true
      leafwe.limits.others: true
      leafwe.resetlimits: true
      leafwe.givelimits: true
  leafwe.use:
    description: Use /set command
    default: true
  leafwe.wall:
    description: Use /wall command
    default: true
  leafwe.replace:
    description: Use /replace command
    default: true
  leafwe.undo:
    description: Use /lwe undo command
    default: true
  leafwe.confirm:
    description: Use /lwe confirm command
    default: true
  leafwe.give:
    description: Use /lwe give command
    default: op
  leafwe.reload:
    description: Use /lwe reload command
    default: op
  leafwe.bypass.limit:
    description: Bypass volume limits
    default: op
  leafwe.bypass.protection:
    description: Bypass WorldGuard/SuperiorSkyblock protection
    default: op